#include "TestEcs.h"
#include "Ecs/ComponentsHandler.h"

DT_REGISTER_COMPONENT(TestEmptyComponent1, TEST_EMPTY_COMPONENT);
DT_REGISTER_COMPONENT(TestEmptyComponent2, TEST_EMPTY_COMPONENT);
DT_REGISTER_COMPONENT(TestDataComponent1, TEST_DATA_COMPONENT_1);
DT_REGISTER_COMPONENT(TestDataComponent2, TEST_DATA_COMPONENT_2)